info:
  contact: {}
paths:
  /api/health:
    get:
      description: Verifica se a API está online
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - System
swagger: "2.0"
