definitions:
  auth.aboutMeResponse:
    properties:
      role:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
  auth.loginRequest:
    properties:
      password:
        example: "123"
        type: string
      username:
        example: user
        type: string
    type: object
  auth.loginResponse:
    properties:
      message:
        example: Login realizado com sucesso
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  auth.logoutResponse:
    properties:
      message:
        example: Logout realizado com sucesso
        type: string
    type: object
  auth.registerRequest:
    properties:
      password:
        example: "123"
        type: string
      username:
        example: user
        type: string
    type: object
  auth.registerResponse:
    properties:
      message:
        example: User created
        type: string
    type: object
  health.healthResponse:
    properties:
      healthy:
        type: boolean
      message:
        example: "On"
        type: string
    type: object
  productIdInfo.product:
    properties:
      application: {}
      code:
        example: FAP-2829
        type: string
      fiscal_data: {}
      id:
        example: 1
        type: integer
      images: {}
      logistic_data: {}
      make:
        example: WEGA
        type: string
      name:
        example: FILTRO DE AR
        type: string
      similar_json: {}
      tech_data: {}
    type: object
  productIdInfo.response:
    properties:
      products:
        items:
          $ref: '#/definitions/productIdInfo.product'
        type: array
    type: object
  products.Product:
    properties:
      appCount:
        example: 1
        type: integer
      code:
        example: FAP-2829
        type: string
      codeNorm:
        example: FAP2829
        type: string
      id:
        example: 1
        type: integer
      image:
        example: https://www.wega.com.br/wp-content/uploads/2020/09/filtro-de-ar-wega-1.jpg
        type: string
      make:
        example: WEGA
        type: string
      name:
        example: FILTRO DE AR
        type: string
      public:
        example: 1
        type: integer
    type: object
  products.ResponseProducts:
    properties:
      products:
        items:
          $ref: '#/definitions/products.Product'
        type: array
    type: object
info:
  contact: {}
paths:
  /auth/aboutme:
    get:
      description: Retorna informações do usuário.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.aboutMeResponse'
      summary: Dados do usuário
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Realiza um login de usuário
      parameters:
      - description: Credenciais
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.loginResponse'
        "400":
          description: Corpo da requisição inválido
          schema:
            type: string
        "401":
          description: Usuário ou senha inválidos
          schema:
            type: string
        "500":
          description: Erro interno do servidor
          schema:
            type: string
      summary: Login
      tags:
      - Auth
  /auth/logout:
    post:
      description: Apaga os cookies do usuário.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.logoutResponse'
      summary: Fazer logout
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Cria um novo usuário.
      parameters:
      - description: Dados do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.registerResponse'
        "400":
          description: Corpo da requisição inválido
          schema:
            type: string
        "500":
          description: Erro interno do servidor
          schema:
            type: string
      summary: Registrar um novo usuário
      tags:
      - Auth
  /products:
    get:
      description: Realiza uma consulta de produtos (id 1 ao `limit`)
      parameters:
      - description: Quantidade máxima de produtos
        in: query
        name: limit
        type: integer
      - description: Somente produtos públicos
        in: query
        name: publicOnly
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/products.ResponseProducts'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Products
      tags:
      - Products
  /products/{id}:
    get:
      description: Retorna todos os dados do produto
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/productIdInfo.response'
        "401":
          description: Unauthorized
          schema: {}
      security:
      - CookieAuth: []
      summary: ProductInfo
      tags:
      - Products
  /system/health:
    get:
      description: Verifica se a API está online
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.healthResponse'
      summary: Health Check
      tags:
      - Health
swagger: "2.0"
